version: "3.9"
services:
  web-nginx:
    restart: always
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  app-flask:
    restart: always
    build: ./
    container_name: flask
    expose:
      - 8080

  db-postgres:
    restart: always
    image: postgres:latest
    container_name: postgres
    environment:
     - POSTGRES_USER:'postgres'
     - POSTGRES_HOST_AUTH_METHOD=trust
     - POSTGRES_DB='EKSAMEN'
    ports:
      - "5432:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data

volumes:
  postgres_db:
