version: '3.9'

services:
  web:
    image: nginx
    container_name: nginx
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "8080:80"

  flask:
    build: "./flask"
    container_name: app
    volumes:
      - "./flask/:/usr/src/app/"

  database:
    image: postgres
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

volumes:
  postgres_data:
